language: generic

sudo: required

services:
 - docker
 
script:
 - docker run --rm -e TB_TOKEN=$TB_TOKEN -e IDS="11504381 449542698" -e BUSCA="atos oficiais" rodolfoneto/diario_itatiba_robo:develop

branches:
  only:
    - develop
    - master
    - docker-v2.0
