language: generic

sudo: required
services:
 - docker
 
script:
 - bash 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
 - docker run --rm rodolfoneto/diario_itatiba_robo:develop

branches:
  only:
    - develop
